name       : perl-file-copy-recursive
version    : '0.45'
release    : 8
source     :
    - https://github.com/drmuey/p5-File-Copy-Recursive/archive/v0.45.tar.gz : 2f3d9d4dda7420d932b4502731f2d5ce3bbc2a13089bee31cbf7046daec48be2
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://github.com/drmuey/p5-File-Copy-Recursive
summary    : File::Copy::Recursive - Perl extension for recursively copying files and directories
description: |
    File::Copy::Recursive - Perl extension for recursively copying files and directories
builddeps  :
    - perl-path-tiny
    - perl-test-deep
    - perl-test-fatal
    - perl-test-file
    - perl-test-warnings
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
