name       : perl-file-copy-recursive
version    : '0.44'
release    : 4
source     :
    - https://github.com/drmuey/p5-File-Copy-Recursive/archive/v0.44.tar.gz : b5674b8ceee34e9724746466d9aefdb6849a9afa68db907077ad9e1279a0bd24
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://github.com/drmuey/p5-File-Copy-Recursive
summary    : File::Copy::Recursive - Perl extension for recursively copying files
    and directories
description: |
    File::Copy::Recursive - Perl extension for recursively copying files and directories
builddeps  :
    - perl-path-tiny
    - perl-test-deep
    - perl-test-fatal
    - perl-test-file
    - perl-test-warnings
    - perl-try-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
