name       : perl-file-copy-recursive
version    : '0.41'
release    : 2
source     :
    - https://github.com/drmuey/p5-File-Copy-Recursive/archive/v0.41.tar.gz : b37e15e26d19868c8a03655905c19d13856e6c3b68c9f97ab48b8c26761b04fc
license    : Artistic-1.0-Perl
component  : programming.perl
homepage   : https://github.com/drmuey/p5-File-Copy-Recursive
summary    : File::Copy::Recursive - Perl extension for recursively copying files and directories
description: |
    File::Copy::Recursive - Perl extension for recursively copying files and directories
builddeps  :
    - perl-file-find-rule
    - perl-file-slurp
    - perl-path-iter
    - perl-path-tiny
    - perl-sub-uplevel
    - perl-test-deep
    - perl-test-exception
    - perl-test-file
    - perl-test-warn
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
